### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mat41997** [BenWoodworth/FastCraftPlus#12]
http://hastebin.com/ugajajenar.avrasm

**Comment by RoboMWM** [comment]
You missed the important part of the error, which was just a few lines below the last line you copied...

**Comment by BenWoodworth** [comment]
Here's the full stack trace reported by someone else:
http://pastebin.com/u1z6GxQb

**Comment by RoboMWM** [comment]
That one is an incorrect array index, not a NPE...?

**Comment by BenWoodworth** [comment]
I just released v0.5. Can you let me know if you're still getting errors?

**Comment by mat41997** [comment]
thanks ^^ no errors
