### ISSUE TITLE
CraftItemEvent

### ISSUE THREAD

**Issue by mat41997** [BenWoodworth/FastCraftPlus#14]
logs
http://hastebin.com/perutagosi.avrasm

**Comment by Cloman** [comment]
I am having the same errors since version 0.4.

**Comment by RoboMWM** [comment]
Might also be nice to mention your spigot/paper/whatever version.

**Comment by BenWoodworth** [comment]
Can you give this a try, and let me know if it fixes the problem?
[FastCraftPlus.zip](https://github.com/BenWoodworth/FastCraftPlus/files/200742/FastCraftPlus.zip)

**Comment by Cloman** [comment]
0.6 works for me no error with opening the table or crafting with it.
Thnx..

**Comment by BenWoodworth** [comment]
Alright. Thanks for reporting it!
