### ISSUE TITLE
Slight delay when right click crafting table

### ISSUE THREAD

**Issue by demonslayer147** [BenWoodworth/FastCraftPlus#15]
This problem did not appeared until you started to add CraftItemEvent calling, along with latest version of [ExtraHardMode](https://www.spigotmc.org/resources/extra-hard-mode.19673/)

Console Spam when right click crafting table [pastebin](http://pastebin.com/fThK5kkp)

Using version 1.9 spigot (21 versions behind according to /version)
Using FastCraft+ v0.6

**Comment by RoboMWM** [comment]
For reference, here's the line that's returning null: https://github.com/MLG-Fortress/ExtraHardMode/blob/master/src/main/java/com/extrahardmode/features/MoreTnt.java#L67

**Comment by BenWoodworth** [comment]
Can you see if you're still getting this error in v0.7

**Comment by demonslayer147** [comment]
All fixed! Thanks

**Comment by BenWoodworth** [comment]
Okay, it's just a performance issue. I'll try to fix this by v0.9
