### ISSUE TITLE
Server Crash and error spamming

### ISSUE THREAD

**Issue by Cloman** [BenWoodworth/FastCraftPlus#16]
Hi After using 0.6 of fastcraft my server crash and i think because of this plugin seeing the crash report.
using spigot 1.9.2
http://hastebin.com/pirujozase.avrasm

After starting the server again with 0.6 im getting spammed with this error and whole server starts lagging:
http://hastebin.com/efuqovifad.avrasm

**Comment by BenWoodworth** [comment]
Can you see if you're still getting this error in v0.7

**Comment by Cloman** [comment]
ok will check .. sorry i did not see 0.7 but now after refreshing i do.

**Comment by Cloman** [comment]
Still getting this spammed : http://hastebin.com/ecubomigoc.avrasm
and if you try to mutch its getting laggy again.

**Comment by Cloman** [comment]
not sure if this helps as it constantly say this plugin with your have a conflict but this is the tools stats.
http://dev.bukkit.org/bukkit-plugins/tool-stats/

**Comment by BenWoodworth** [comment]
I'll take a look at its code to see what's causing the problem. This is the only error you're getting?

**Comment by Cloman** [comment]
over and over and over till it lags and possibly also caused the crash if lots of players triggers the error.

**Comment by BenWoodworth** [comment]
I just released v0.8, and it's compatible with ToolStats for me. Let me know how it works.

**Comment by Cloman** [comment]
ok will check .. atm to many players so cant do it right now.

**Comment by Cloman** [comment]
ok just updated to 0.8.
Look good as errors are gone for now.
Will run it for 2 days and give you feedback on it again so i can gather some results also from other players.

As while testing i still had some strange behavior with it like slow response when you click for example the crafting table for crafting grid.
At a certain point i was even able to get the crafting table in my own inventory for the crafting grid.

**Comment by RoboMWM** [comment]
Performance issues mentioned here: https://github.com/BenWoodworth/FastCraftPlus/issues/19 and https://github.com/BenWoodworth/FastCraftPlus/issues/15 (not sure why the guy changed the title of that ticket, he had a different issue before which was resolved)

**Comment by BenWoodworth** [comment]
Performance has been improved greatly for v0.9.

**Comment by Cloman** [comment]
ok just to add a finishing note to this closed ticket and already outdated fastcraft+ 0.8.
0.8 seems to be fine no errors anymore or crashes.
