### ISSUE TITLE
cannot resolve plugin dependencies

### ISSUE THREAD

**Issue by RoboMWM** [BenWoodworth/FastCraftPlus#17]
So, thanks to people clamoring for premium plugin integration, I can no longer build this plugin via maven anymore D:

Not sure of solutions right now, since I'm sure those authors aren't going to setup maven repos or make a plugin specifically for their API or the like. Maybe a branch without the dependencies, though not sure how willing you'd be to maintain two different branches :/

**Comment by BenWoodworth** [comment]
You can get the api for ProRecipes for free, but you'll have to ask the developer of Item Maker Pro to make one.

**Comment by BenWoodworth** [comment]
The developer of Item Maker Pro said he'll be releasing an API jar sometime soon.

**Comment by RoboMWM** [comment]
How are you compiling this without referencing either plugin/API in your pom?

**Comment by RoboMWM** [comment]
https://www.spigotmc.org/threads/item-maker-pro-paid.66629/page-31#post-1509938

On top of the vibe I'm getting that all he cares for is money, so making an API plugin probably doesn't seem to be worth it for him... not sure if I should fork and strip out item maker pro stuff, but perhaps having a build server could help partially.

**Comment by BenWoodworth** [comment]
I'm compiling against the ProRecipes api jar, and the Item Maker Pro plugin jar. I think I'll change the code to use reflection, so they're not needed when compiling.

**Comment by RoboMWM** [comment]
Alright, thanks! Still wondering how you're "compiling against" those plugins without specifying it in the pom though

**Comment by BenWoodworth** [comment]
I'm using IntelliJ, and I can specify jars as libraries.

**Comment by BenWoodworth** [comment]
I changed the Item Maker Pro compatibility to use reflection. I'll change ProRecipes too later if you want me to, but you can use its api jar for now.
https://www.spigotmc.org/wiki/prorecipes-recipeapi/?noRedirect=1

**Comment by RoboMWM** [comment]
It's fine, will see if I can add that successfully in the pom.

**Comment by BenWoodworth** [comment]
What IDE are you using?

**Comment by RoboMWM** [comment]
IntelliJ

**Comment by BenWoodworth** [comment]
You can try this
File -> Project Structure
Under project structure, select Libraries.
Click the green + button on the top left, and choose Java.
Select the ProRecipes API jar.

**Comment by RoboMWM** [comment]
Well the reason why one would use maven is because maven is a dependency manager. Anyways, my PR works and I see you pulled it, thanks!
