### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by RoboMWM** [BenWoodworth/FastCraftPlus#19]
Upon placing a bunch of materials in my inventory (resulting in three pages of fastcraft results), then attempting to open, close, and re-open the crafting bench causes lag between the second time I attempt to open the crafting bench. In fact, just when I was about to test this very thing one more time, the watchdog ended up killing my server due to FastCraft+: https://gist.github.com/RoboMWM/8acee8159b2781f11a9a71a76afea28e

**Comment by RoboMWM** [comment]
I'm wondering if this is because you're figuring out the recipes differently than the prior version, hence it triggering the fastclick and the like - as if you're "manually" making the recipes by simulating the crafting of them?

**Comment by BenWoodworth** [comment]
I'm working on fixing performance for the next release. Right now, it's triggering crafting events for every recipe on the server every time the inventory opens. I'm working on changing that now

**Comment by RoboMWM** [comment]
Curious if you could state (or summarize) the difference between this and the older plugin regarding how you find recipes - or is this the only differentiator?

**Comment by BenWoodworth** [comment]
That's the only major difference

**Comment by BenWoodworth** [comment]
Performance has been improved in v0.9.
