### ISSUE TITLE
Custom Recipe/Smelt plugin + Jobs compatibility results.

### ISSUE THREAD

**Issue by Coldene** [BenWoodworth/FastCraftPlus#21]
Craft Creator v1.0.0 for CB 1.6.4-R2.0 Nov 05, 2013 (lol)
http://dev.bukkit.org/bukkit-plugins/craft-creator/
CraftCreator ancient plugin injects a yml config listing 
recipe and smelts into know recipes and smeltables.
It works perfectly in Spigot 1.9.2

I Added 20 or so smeltables and recipe items.
All the items added appear in the FastCraftPlus interface. :+1: 
(Also did in FastCraft in 1.8)  **Grats on the brilliant
idea of adding custom recipe ability for the future of FastCraft.**

:question:  
Jobs Spigot 1.8
Event, craft item, paying Exp and or Eco money to player.
In 1.8 these crafts through the FastCraft interface pay Jobs Exp 
every time but the player has to do single crafts and hold shift while crafting.

**BIG TISSUE ISSUE **
Jobs v2.63.1 using Spigot 1.9.2 (Paper build 616)
ALL craft events through FastCraftPlus in 1.9.2 no longer seem to tell Jobs 
something was crafted or jobs changed it's craft listener?? :ghost: 
No Exp is paid for all crafts. The normal workbench still pays it though.

**MINI TISSUE **
If you should add a sound effect to the craft event, make it tiny, short and have
and internal cooldown or toggle or even permission required? 
I have 1300+ spells on my server that add sound effects stuff to many events.
I'm used to alot of noises...
Frankly the many seconds long hissing sound effect on craft event is a bad idea imo!
It also adds to client side lag a tiny bit if spammed in a short time. Like spamming many
stacks going for personal speed record. I'm guessing you're atm testing the ability 
to get craft event to do other stuff like play sound and that effect is just temporary. Ya!
Even if it was the best sound effect in the game like sweet melody.. it would get boring
quickly on a server featuring a psychotic amount of custom crafts and craft reward events.
Fix dat sound mon.
 /hopeandwishaponastarallnight :santa: 

My other plugins are not currently throwing any tantrums about FastCraftPlus events.
Running smoother than a baby hero's chin. :baby: 

They include;
CoreProtect, WorldEdit, Essentials, GroupManager, NoSignHack, ClearLag, FastCraftPlus, Votifier, WorldGuard, ProtocolLib, Multiverse-Core, Craft_Creator, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, mcMMO, Vault, GAListener, EssentialsSpawn, MagicSpells, dynmap, MagicSpellsShop, MyPet, Dynmap-Essentials, Autorank, Jobs, WorldBorder, PerWorldInventory, HolographicDisplays, LWC, PreciousStones, SilkSpawners, SignLogger, AutoPickup, AdvancedAchievements, PlayerVaults, Dynmap-PreciousStones, MyPreciousStone, ChestShop

FUTURE YAY
**It would be VERY cool if FastCraftPlus could call up items from 
MyPet inventories and PlayerVaults or even enderchest? !!!
You may also want to add some option of overriding the
essentials /workbench and player vaults /workbench
to open the FastCraftPlus + FastCraft more advanced interface.**

Bukkit for life. Spigot is only eversnapshot? It STILL has a
tiny plugin selection compaired to Bukkit/curse. Spigot site 
plugin search ability is simply dire.
Choooose life, chooooose Bukkit! For FastCraftPlus that is?
Yrs I use Spigot lol. JUst saying... Bukkit/curse is also where the 
download counts are at ;D.

Yes,
I have to say also, THANKS, sweet plugin. 
Congrats translating to 1.9 :+1: 

May your code NEVER bully you.. or 
do a trollface in the matrixgreentext at you...
Like mine :D. Thanks for reading this.

**Comment by RoboMWM** [comment]
You might want to separate each request in a separate issue, though not sure what BenWoodworth desires.

_grumbles on about players desiring focus away from vanilla bug-fixing_

**Comment by BenWoodworth** [comment]
I quite like the long post. It's a nice dialogue. Though it might be more useful split up into different issues lol.

**Jobs**: I have gotten reports of Jobs throwing errors when items are crafted through the FastCraft+ interface, so I am looking into that. If you have any errors in the console, feel free to share them.

**Sounds**: I'm thinking of adding sound customization (change the sounds to what you want, or disable them entirely), so you will have control over what sounds are played when buttons in the interface are clicked.

**Other Inventories**: I don't think I'll be adding support for ender chests, or other plugins' inventories.

**Comment by Coldene** [comment]
Hi
Thanks for the reply.

I wish I had any console / log errors regarding the Jobs no more Exp pay.
There are none. (yay?)
http://dev.bukkit.org/bukkit-plugins/jobs-reborn/
is the actual Jobs I use not the Original.

It has a plugin API thing for JobsExpGainEvent apparently.
It would be good to get the crafting Exp back but it
works fine with the normal workbench still so NP.

Beware with sounds and stuff. 1.8 to 1.9 changes. Most sound names 
changed and thus made many plugins immediately break or
cause errors in effects where they would otherwise not have.

Cheers for the reply, great job with the plugin!

**Comment by BenWoodworth** [comment]
I'll be looking into jobs, and I've already made sure sounds are compatible 👍
