### ISSUE TITLE
Only 1 oak wood plank per 1 oak log

### ISSUE THREAD

**Issue by claes-n** [BenWoodworth/FastCraftPlus#22]
Fix by adding the following into recipes.yml:

# 1 oak log -> 4 oak planks
oak_wood_planks:
  type: shapeless
  ingredients:
    log: [1, 'minecraft:log']
  result: [4, 'minecraft:planks']

**Comment by BenWoodworth** [comment]
I'm not having this issue. Can you share what other plugins you're using? Also try this on a test server with only FastCraft+ to see if it is still a problem.
