### ISSUE TITLE
Other Custom Crafting Plugins

### ISSUE THREAD

**Issue by mat41997** [BenWoodworth/FastCraftPlus#24]
# Description
http://dev.bukkit.org/bukkit-plugins/advanced-lucky-block/
i not can craft the lucky block

# Server/FastCraft+ Versions
PaperSpigot 1.8.8
FastCraft+ v0.12
Java 9 113

# Stack Trace
no error

Plugins (50): Grenade, FastCraftPlus, LuckyBlock, CustomRecipes, SkinsRestorer, HorseTpWithMe, Simple-AutoSave, AntiJoinBot, ViaVersion, Tablist, SilkChests, Titlebar, AsyncWorldEditInjector, WorldEdit, EggCatcher, Skript, PluginManagerReloaded, SkQuery, RandomTP, Cinema, ProtocolLib, LibsDisguises, NoCheatPlus, ImageMaps, Shopkeepers, HugeItems, WildSkript, BlocksHub, PermissionsEx, StaffChat, Vault, MassiveCore, LogBlock, CreativeGates, HolographicDisplays, WorldGuard, BlocksHub-WorldGuard, ChestCommands, LockettePro, EditableSign, BlocksHub-LogBlock, Essentials, SexyMotd, PreciousStones, AsyncWorldEdit, ColoredTags, EssentialsChat, EssentialsSpawn, Smileychat, AuthMe

**Comment by BenWoodworth** [comment]
Can you explain why Custom Recipes is incompatible with FastCraft+

**Comment by mat41997** [comment]
i not can crafted : P

**Comment by BenWoodworth** [comment]
Can you share what recipe it is? (What items go in, and what comes out)

**Comment by mat41997** [comment]
sorry, false alarm, work it, is good : > 
thanks : P
