### ISSUE TITLE
Workbench button disables FastCraft+ interface

### ISSUE THREAD

**Issue by Phreag** [BenWoodworth/FastCraftPlus#29]
Version: Fastcraft+ 0.13
Latest Paper build (1.9.2)

When i use a workbench and click the button for the classical crafting grid it does not enable me to get the fastcraft gui back. when i open a new workbench it still has the usual 3x3 grid.
Relog does not change anything.

**Comment by adnurmal** [comment]
Version: Fastcraft+ 0.13
Latest Spigot build (1.9.2)

Same issue as noted above. Unable to get the GUI back.
