### ISSUE TITLE
i not can crafted the diamond block with gui

### ISSUE THREAD

**Issue by mat41997** [BenWoodworth/FastCraftPlus#33]
no error

image
http://imgur.com/IzS7F6L

command
/i diamond 32 name:Dajmenty

paperspigot 1.8.8, plugin viaversion, essentials, fastcraft+ v0.13 and other..

**Comment by BenWoodworth** [comment]
FastCraft+ will not craft items using ingredients with custom names, etc. if the recipe requires normal items.
