### ISSUE TITLE
Commands Issue

### ISSUE THREAD

**Issue by AcesGamingUK** [BenWoodworth/FastCraftPlus#34]
/fastcraft toggle
/fastcraft craft

but return nothing

other the displaying the command in whit in the chat

http://prntscr.com/as7xcs

**Comment by BenWoodworth** [comment]
These have not been implemented yet, but will be soon.

**Comment by AcesGamingUK** [comment]
just informing you as this overrides /craft with the fastcraft /craft (that doesn't work)

**Comment by RoboMWM** [comment]
If you need to remap commands, just use the commands.yml file. http://wiki.bukkit.org/Commands.yml

**Comment by AcesGamingUK** [comment]
already did that as a temporary solution

just informing you that its assigning commands to the plugin even though the plugin has no commands

**Comment by BenWoodworth** [comment]
I'm going to be disabling the commands until they are implemented.

**Comment by AcesGamingUK** [comment]
sounds like a good shout

**Comment by AcesGamingUK** [comment]
also the perm fastcraft.use doesn't seem the be fully working as people who don't have the perm can still use gui
instead i've had to negate the perm the deny them

**Comment by BenWoodworth** [comment]
This is the intended functionality.
This permission is default:
https://github.com/BenWoodworth/FastCraftPlus/blob/master/src/main/resources/plugin.yml#L38-L40
