### ISSUE TITLE
New Version Error with Gui

### ISSUE THREAD

**Issue by AcesGamingUK** [BenWoodworth/FastCraftPlus#41]
New Version Error with Gui

Error
http://hastebin.com/zokixamosu.avrasm

debug
http://hastebin.com/xalulomiqi.vbs

fastcraft version
FastCraft+ v0.19

Spigot version
1.8.8

**Comment by BenWoodworth** [comment]
Can you see if you get the error with this?
[FastCraftPlus.zip](https://github.com/BenWoodworth/FastCraftPlus/files/233163/FastCraftPlus.zip)

**Comment by AcesGamingUK** [comment]
just tested and currently no errors

**Comment by BenWoodworth** [comment]
Okay, thanks!
