### ISSUE TITLE
Re-sorting does not work

### ISSUE THREAD

**Issue by ShinyYveltal** [BenWoodworth/FastCraftPlus#46]
# Description
When I click on the nether star, the items do not get automatically sorted.

# Debug Output

[FastCraftPlus] FastCraft+ Debug Info:

========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.19.1
  git-Spigot-d20369f-7fc5cd8 (MC: 1.9)
  1.9-R0.1-SNAPSHOT
  Java 1.8.0_77
Other Plugins (28):
  AdminFun 2.4.7
  Advanced_Item_Effects 1.4.1
  AlphaChest 1.16.0
  Auctions 2.4.1-SNAPSHOT
  BoatDrop 0.4
  ChestShop 4.0-r5
  ClearLag 2.9.0
  Craftconomy3 3.3-e72ac42-trv178
  EnchantedFurnace 1.5.1
  Essentials 2.0.1-b330
  EssentialsChat 2.0.1-b342
  EssentialsSpawn 2.0.1-b342
  HolographicDisplays 2.1.12
  ItemBank 2.4.1
  KingKits 5.2.5
  Lockette 1.8.21
  Macros 1.0
  NBTEditor 2.0-SNAPSHOT
  PermissionsEx 1.23.4
  RandomTeleport 5.0.2
  Scavenger 1.7-2
  Shop 2.0.4
  Simple-AutoSave 0.2.2
  Trading 3.2
  TrashCan 1.2.0
  Vault 1.5.6-b49
  WorldEdit 6.1;no_git_id
  WorldGuard 6.1
===========================================

**Comment by RoboMWM** [comment]
Explain what you mean by "sorted."

**Comment by ShinyYveltal** [comment]
The items, if an empty slot is present, should organize themselves when you click on the nether star. I found that on the latest version of the plugin, the nether star did not do anything.

**Comment by BenWoodworth** [comment]
This is an issue. It looks like the refresh button isn't doing anything.

**Comment by BenWoodworth** [comment]
This is fixed for the next update.
