### ISSUE TITLE
Server Thread Errors Missing [handle] section in recipes.yml

### ISSUE THREAD

**Issue by Inysal** [BenWoodworth/FastCraftPlus#51]
# Description
[Server thread/ERROR]: [FastCraftPlus] §cMissing 'hashes' section in recipes.yml
[Server thread/ERROR]: [FastCraftPlus] §cMissing 'results' section in recipes.yml
[Server thread/ERROR]: [FastCraftPlus] §cMissing 'ingredients' section in recipes.yml
****FastCraft seems to work fine.**** Just Server displaying message.

# Debug Output
========== FastCraft+ Debug Info ========== Versions: FastCraft+ v0.20.1 
git-Spigot-e6f93f4-935f18b (MC: 1.9.2) 
1.9.2-R0.1-SNAPSHOT 
Java 1.8.0_60 
Other Plugins (22): 
bChatManager 3.1.2 
ChatColor2 1.6.8 
ClearLag 2.9.1 
CoreProtect 2.12.0 
CustomEnderChest 1.1.1 
iConomy_Recreation 8.0 
LagMonitor 1.3 
LockettePro 2.1.3 
Orebfuscator4 4.0.9-SNAPSHOT 
PermissionsEx 1.23.4 
RPGMobMoney 1.3.1 
SeePlayerInventory 1.7 
SignEdit 3.3.2 
SignShop 2.11.0 
SimpleHomes 2.0.3 
SimpleSort 1.4 
StarterKit 1.3.7-SNAPSHOT 
SurvivalFly 1.0 
TreeAssist 5.10.1 
UberEnchant 3.1 
Vault 1.5.6-b49 Vote 1.903

**Comment by BenWoodworth** [comment]
This shouldn't cause any problems. It's just an output message.

**Comment by BenWoodworth** [comment]
Fixed in v0.20.3
