### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by PeRFecTxTabZ** [BenWoodworth/FastCraftPlus#59]
# Description
Hello, only the permissions group VIP have the permissions group fastcraft.use, but every player can use it. it worked finde with fastcraft but with fastcraft plus there is this bug :(

# Debug Output
<details><summary>Show **/fcadmin debug** output</summary>
```
========== FastCraft+ Debug Info ==========
Versions:
FastCraft+ v0.20.5
git-Bukkit-12698ea (MC: 1.8.8)
1.8.8-R0.1-SNAPSHOT
Java 1.7.0_71
Other Plugins (28):
ActionHealth 3.2
AdvancedBan 10.3
BukkitSpeak 0.68-b238
Commandspy 4.1.0
Cop 1.3d
CoreProtect 2.12.0
DeathMessages 3.1.1
Essentials TeamCity
EssentialsAntiBuild TeamCity
EssentialsChat TeamCity
EssentialsSpawn TeamCity
HideAndCustomPlugins 1.4.8
HolographicDisplays 2.1.12
iConomy 7.0
NoCheatPlus 3.13.7-RC-sMD5NET-b925
PermissionsEx 1.23.4
PlugMan 2.1.1
ProReports 1.2
ProtocolLib 3.6.5
RedProtect 6.5.81
ScoreboardStats 0.9.8
Tablist 1.3.0.2
Trading 3.2
TrailGUI 4.3
Vault 1.5.6-b49
WorldEdit 6.1;no_git_id
WorldGuard 6.1
ZavAutoMessager 3.2
===========================================
```
</details>

**Comment by BenWoodworth** [comment]
The permission fastcraft.use is true for all players by default. Instead of giving this permission to VIP's, try removing it from normal players. It should be something like this:
`- -fastcraft.use`

**Comment by PeRFecTxTabZ** [comment]
why are these by default :/ Can u change these? this is only causing me problems :( When they Tipe /fastcraft toggle it says at first they do not have permissions and under that it says that it was suggesfull .. sry for my english :(

**Comment by BenWoodworth** [comment]
I have them default so it can be used without using permissions. I may change it in the future.

**Comment by PeRFecTxTabZ** [comment]
Ok, thank  you I really appreciate that. :)

**Comment by BenWoodworth** [comment]
For now, negating the permission should work fine.
