### ISSUE TITLE
Cannot open GUI by right clicking the craft table

### ISSUE THREAD

**Issue by TANJX** [BenWoodworth/FastCraftPlus#65]
# Description
- <s>No Armor/Fireworks/multiplier buttons in GUI, only craft grid and refresh buttons are displayed (items can be crafted properly)</s>
- I cannot open GUI by right clicking the craft table. I am sure I toggled on by using `/fc toggle on`
- Some strings from the language file are not implemented in the message system

# Debug Output
<details>
```
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.21
  git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8)
  1.8.8-R0.1-SNAPSHOT
  Java 1.8.0_45
Other Plugins (15):
  Essentials 2.0.1-b266
  GroupManager Pre2.14.1.3 FINAL (Phoenix)
  ProtocolLib 3.6.5
  Residence 2.6.7.0
  Vault 1.2.31-b411
===========================================
```
</details>

**Comment by BenWoodworth** [comment]
The missing gui buttons haven't been implemented yet. They're still a work in progress.

Does the gui open when you run the /craft command?

And which missing strings are you thinking of?

**Comment by TANJX** [comment]
Thanks for your quick reply ;-)
Yep, the GUI works fine when I use `/craft` or `/fc craft`
Those strings are missing:
- commands.player-only
- commands.console-only
- commands.no-perm
- commands.unknown-player
- commands.fastcraftadmin reload.output
Also, for the following message, `<player>` is not replaced with player's name and should be sent to console instead of the player
- commands.fastcraft toggle.output.on-other
- commands.fastcraft toggle.output.off-other

**Comment by TANJX** [comment]
In addition, here is the localization in Chinese (简体中文):
https://gist.github.com/TANJX/d47ee7f7de04e496d736f1f0ec01f50f

You can put it into your plugin/language folder by committing my name.

**Comment by BenWoodworth** [comment]
It looks like you need to give players the fastcraft.use permission. I found a bug that lets people open the FastCraft+ interface with the /craft command, even if they don't have that permission.

I'm also not sure what you mean when you say the strings are missing. They're in the EN.yml file.

And thanks for the translation. I appreciate it!
