### ISSUE TITLE
Shown Error with Multiplikator

### ISSUE THREAD

**Issue by CloudeLecaw** [BenWoodworth/FastCraftPlus#72]
# Description
If u re moe then one Stack as a result the Game show this as -1

# Stack Trace
To reproduce take one stack wood into your inventorey and open the FC-Workbench
klick the multiplilator until the results would be more then 64 pices

http://www2.pic-upload.de/img/30915363/2016-06-12_04-27-56.png

Edit:

2nd Bug:
A Middleclick does not redurce to 1 like in the description.
It does increase the Crafting-Multiplicator to 64

**Comment by BenWoodworth** [comment]
That's the intended functionality. I can't make the items show more than 64, so it says -1 instead. You will still get the right number of items, and you can see how many items will be crafted if you hover over the item.
