### ISSUE TITLE
Banners missing

### ISSUE THREAD

**Issue by CloudeLecaw** [BenWoodworth/FastCraftPlus#75]
Bannerrecipes for the big amount of Banners cant be shown currently by FastCraft+

You may should add this as a todo point :-)

**Comment by BenWoodworth** [comment]
I decided not to add banners. There are a lot of banner possibilities, and if they showed up in the interface, you would just see random patterns. I thought it would be better to leave banner crafting to the crafting grid.

**Comment by Jikoo** [comment]
If you change your mind, [BannerMaker](http://dev.bukkit.org/bukkit-plugins/bannermaker/) has a pretty clean UI for it. That said, it'd require a decent bit of additional work that's somewhat out of the scope of this plugin's normal functions.

**Comment by BenWoodworth** [comment]
I'm definitely not going to add banners to the main FastCraft+ interface with the rest of the recipes. I like the sound of an interface to assist in creating banners, so I may add that sometime in the distant future.
