### ISSUE TITLE
Permissions question

### ISSUE THREAD

**Issue by qqmpzz** [BenWoodworth/FastCraftPlus#82]
I'm sure this is something simple, but I cannot seem to get FastCraft+ to work in my hosted server. The jar file is in the plugins folder, and the subfolder was created. When I open the config.yml file there is a line that is not commented out, that reads "default-enabled: true", yet after restarting the server, in game nothing is different with the crafting system, despite the plugin showing as being in use in "/plugins".
I am sure there is a simple setting I am missing, but I am clueless as this is the first server I've ever used, and the first plugin I've ever tried to use. Any remedial help would be appreciated.

**Comment by BenWoodworth** [comment]
Did you give your players permissions for FastCraft+?
To use the interface, players need to have the fastcraftplus.use permission.
You can find a list of permissions here:
https://github.com/BenWoodworth/FastCraftPlus/blob/master/README.md

**Comment by qqmpzz** [comment]
Thanks for the fast response. And again, I apologize if this is basic stuff, but I am totally clueless. How do I give players that permission? Are there additional lines I need to add to the config.yml? I saw the list of permissions, I just don't know how/where to implement them?

**Comment by BenWoodworth** [comment]
You can add permissions in the permissions.yml file. Here's an example:
```
FastCraftPerms:
       description: 'Permissions for FastCraft+'
       default: true
       children:
          fastcraft.use: true
```
And you can add other permissions under children.

**Comment by qqmpzz** [comment]
Thank you so much, works like a charm! Enjoying the plugin immensely already. As a very infrequent player, plugins like this make the game much more enjoyable since I don't have to spend all my time searching for recipes.

**Comment by BenWoodworth** [comment]
You're very welcome! Please feel free to ask for help if you have trouble with anything else. :)
