### ISSUE TITLE
Duplicate items!

### ISSUE THREAD

**Issue by sufletzel** [BenWoodworth/FastCraftPlus#86]
# Description
Players can take items from crafting...

# Debug Output
<details><summary>Show **/fcadmin debug** output</summary>
```
22.10 08:34:54 [Server] INFO Java 1.8.0_25
22.10 08:34:54 [Server] INFO 1.10.2-R0.1-SNAPSHOT
22.10 08:34:54 [Server] INFO git-Spigot-455072c-2f5bda8 (MC: 1.10.2)
22.10 08:34:54 [Server] INFO FastCraft+ v0.25
22.10 08:34:54 [Server] INFO Versions:
22.10 08:34:54 [Server] INFO ========== FastCraft+ Debug Info ==========
22.10 08:34:54 [Server] INFO [FastCraft+] FastCraft+ Debug Info:
```

**Comment by BenWoodworth** [comment]
Thanks for the report. Could you describe click by click how to reproduce this? Including what items are in your inventory, and what you see in the FastCraft+ interface.

**Comment by sufletzel** [comment]
add me on skype>> sufletzel919
and I will show you!

**Comment by BenWoodworth** [comment]
We were unable to reproduce the duplication bug. I will re-open this issue if you can figure out how to reproduce it again.
