### ISSUE TITLE
Bug: FastCraftPlus doesn't work

### ISSUE THREAD

**Issue by anhcraft** [BenWoodworth/FastCraftPlus#88]
A few days now, I don't see it work when I click on an inventory (but it work fine when I use **/fastcraft craft**). I tried to add permissions but it still doesn't work  :(
_Note_: I use the newest version on Spigot 1.9.4 server.

**Comment by BenWoodworth** [comment]
Hi. Can you run the command "/fcadmin debug" and copy the output here? It will help me figure out what might be causing the problem.

**Comment by anhcraft** [comment]
Okay, here's the output: http://pastebin.com/EWhhQ1qT

**Comment by BenWoodworth** [comment]
Have you tried toggling FastCraft+ with this command?
/fc toggle

**Comment by anhcraft** [comment]
I tried but it didn't work and I also found that: FastCraft+ interface show up, then back to the default interface, probably due to the plugin?

**Comment by BenWoodworth** [comment]
That's interesting. If you copy your server, and remove all plugins except for FastCraft+ and your permissions plugin, are you able to view the interface? It's possible that there's some interference with another plugin.

**Comment by anhcraft** [comment]
I feel this error very confusing :(
I disabled the [AquaWarp ](https://www.spigotmc.org/resources/aqua-warp-placeholders-support.29982/) plugin and FastCraft+ worked in my server.
then I created a new server, only include it and FastCraft +, it still works (troll?)

**Comment by anhcraft** [comment]
I solved that problem successfully by creating and using a new plugin called FixFastCraftPlus. It will run the command /fc craft when player left-clicks on a workbench and has permission.
https://mega.nz/#!GAFGDKwB!zGV7jnBvQ41PeQTYJlqhvtgtOQXryHzrDQNPa00QINA

Thanks for helping me and I hope you can create more great plugins! :)

**Comment by BenWoodworth** [comment]
This is definitely just a temporary workaround. I'll see if there is any conflict with AquaWarp, and what might be causing the interface to not open.

**Comment by anhcraft** [comment]
you can see the source at https://github.com/anhcraft/AquaWarp/blob/master/vn/anhcraft/aquawarp/GUI/WarpGUI.java
and https://github.com/anhcraft/AquaWarp/blob/master/vn/anhcraft/aquawarp/Listeners/ClickWarpGUI.java

**Comment by Jikoo** [comment]
AquaWarp is cancelling all interaction other than left clicking blocks. [This line](https://github.com/anhcraft/AquaWarp/blob/c0b34d9d662d101ff7aa1494893535f6e5465438/vn/anhcraft/aquawarp/Listeners/SignWarp.java#L82).

**Comment by anhcraft** [comment]
Hmm. I will fix it.
