### ISSUE TITLE
Plugin does not work in 1.11 ( New version spigot doesn't craft with fastcraft )  

### ISSUE THREAD

**Issue by MoCaveman** [BenWoodworth/FastCraftPlus#91]
# Description
Not surprising that a fantastic plugin like fastcraft has minor repairs needed to version 1.11
Spigot came out with version 1.11 a few hours ago.  

So more for informational purposes than to actually complain... 

Thanks for your hard work. 

# Debug Output
<details><summary>Show **/fcadmin debug** output</summary><pre><code>
{In your server console, run the command "fcadmin debug", and put the output here}
</code></pre></details>

# Stack Trace
<details><summary>Show stack trace</summary><pre><code>
17.11 08:35:24 [Server] INFO ... 17 more
17.11 08:35:27 [Server] INFO MoCaveman issued server command: /fc
17.11 08:35:31 [Server] INFO MoCaveman issued server command: /fastcraft
17.11 08:35:34 [Server] INFO MoCaveman issued server command: /craft
17.11 08:35:34 [Server] ERROR null
17.11 08:35:34 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'craft' in plugin FastCraftPlus v0.26.3
17.11 08:35:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
17.11 08:35:34 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
17.11 08:35:34 [Server] INFO Caused by: java.lang.NullPointerException
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.config.LanguageConfig.gui_itemName(LanguageConfig.java:185) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.craftgui.buttons.GUIButtonRecipe.getItem(GUIButtonRecipe.java:56) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.api.gui.GUIButton$GUIButtonCopy.<init>(GUIButton.java:67) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.api.gui.GUIButton.copy(GUIButton.java:54) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.api.gui.GUI.updateLayout(GUI.java:140) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.craftgui.GUIFastCraft.updateLayout(GUIFastCraft.java:103) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:54) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.commands.CmdCraft.open(CmdCraft.java:52) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.commands.CmdCraft.onCommand(CmdCraft.java:33) ~[?:?]
17.11 08:35:34 [Server] INFO at co.kepler.fastcraftplus.commands.CommandManager.onCommand(CommandManager.java:46) ~[?:?]
17.11 08:35:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom.jar:git-Spigot-d60de0a-a951a88]
17.11 08:35:34 [Server] INFO ... 15 mor
</code></pre></details>

**Comment by BenWoodworth** [comment]
I'll take a look at it later. Thanks for reporting the issue!

**Comment by BenWoodworth** [comment]
Give the latest update a try. Please let me know if you come across any other bugs.
